version: '3.5'

services:
  rabbitmq:
    restart: always
    image: rabbitmq
    ports:
      - "5672:5672"
    networks:
      - my_net

  redis:
    restart: always
    image: redis
    networks:
      - my_net

  apis:
    restart: always
    build:
      context: .
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py test &&
             python manage.py runserver 0.0.0.0:8000"
    networks:
      - my_net
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - redis
    environment:
      - SERVER_PORT=8000
      - SIGNING_KEY=${SIGNING_KEY}
      - VERIFYING_KEY=${VERIFYING_KEY}
    env_file:
      - .env

  websockets:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile2
    command: >
      sh -c "python server.py"
    networks:
      - my_net
    env_file:
      - .env

  xmpp_client:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile3
    networks:
      - my_net
    env_file:
      - .env

networks:
  my_net: {}
