version: '3.5'

services:
  rabbitmq:
    restart: always
    image: rabbitmq
    networks:
      - my_net

  redis:
    restart: always
    image: redis
    networks:
      - my_net

  apis:
    restart: always
    build:
      context: .
    command: ./docker-entrypoint.sh
    networks:
      - my_net
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - rabbitmq
      - websockets
    environment:
      - SERVER_PORT=8000
      - SIGNING_KEY=${SIGNING_KEY}
      - VERIFYING_KEY=${VERIFYING_KEY}
    env_file:
      - .env

  websockets:
    restart: always
    build:
      context: .
      dockerfile: websocket_server_dockerfile
    command: >
      sh -c "python websocket_server.py"
    networks:
      - my_net
    depends_on:
      - xmpp_client
    env_file:
      - .env

  xmpp_client:
    restart: always
    build:
      context: .
      dockerfile: xmpp_client_dockerfile
    networks:
      - my_net
    env_file:
      - .env

networks:
  my_net: {}
